In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
iris=pd.read_csv("iris.csv")

In [4]:
x=iris.iloc[:,:-1].values
y=iris.iloc[:,4].values

In [10]:
print(iris.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [11]:
print(iris.describe())

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [14]:
print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [5]:
from sklearn.model_selection import train_test_split


In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [9]:
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)


In [16]:
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         7
  Versicolor       0.86      0.92      0.89        13
   Virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.91        30
weighted avg       0.90      0.90      0.90        30



In [21]:
print(confusion_matrix(y_test,y_pred))

[[ 7  0  0]
 [ 0 12  1]
 [ 0  2  8]]


In [18]:
from sklearn.metrics import accuracy_score

In [19]:
print("accuracy",accuracy_score(y_test,y_pred))

accuracy 0.9


In [20]:
df=pd.DataFrame({'real value':y_test,'predicted value':y_pred})
df

real value predicted value
0    Virginica       Virginica
1       Setosa          Setosa
2   Versicolor      Versicolor
3    Virginica      Versicolor
4       Setosa          Setosa
5    Virginica       Virginica
6   Versicolor      Versicolor
7    Virginica       Virginica
8    Virginica       Virginica
9       Setosa          Setosa
10      Setosa          Setosa
11      Setosa          Setosa
12  Versicolor      Versicolor
13   Virginica       Virginica
14      Setosa          Setosa
15  Versicolor      Versicolor
16   Virginica       Virginica
17   Virginica      Versicolor
18      Setosa          Setosa
19  Versicolor      Versicolor
20  Versicolor      Versicolor
21  Versicolor      Versicolor
22  Versicolor      Versicolor
23  Versicolor      Versicolor
24  Versicolor      Versicolor
25  Versicolor      Versicolor
26   Virginica       Virginica
27   Virginica       Virginica
28  Versicolor      Versicolor
29  Versicolor       Virginica